spring.application.name=sprigchallenge

spring.security.user.name=syl
spring.security.user.password=123


# props
syl.test=Random Dynamic Text! :D

# logging
logging.file.name=logs/app.log
logging.level.com.sylvie.sprigchallenge=DEBUG
logging.logback.rollingpolicy.file-name-pattern=logs/app.%d{yyyy-MM-dd}.%i.log.gz
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=7