spring.application.name=sprigchallenge

spring.security.user.name=syl
spring.security.user.password=123

# logging
logging.file.name=logs/app.log
logging.level.com.sylvie.sprigchallenge=WARN
logging.logback.rollingpolicy.file-name-pattern=logs/app.%d{yyyy-MM-dd}.%i.log.gz
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=7

#db
spring.datasource.url=jdbc:postgresql://localhost:5433/student_tracker
spring.datasource.username=user1
spring.datasource.password=password123
spring.datasource.driver-class-name=org.postgresql.Driver

#hibernate
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update