services:
  postgres:
    image: postgres:16-alpine
    container_name: challenge_db
    restart: always
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: challenge_database
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    shm_size: 128mb

volumes:
  postgres_data:

